# Chinese (Simplified) Language default config translated by StarYunmeng
# https://www.spigotmc.org/members/staryunmeng.589461/
# Replace the original "config.yml" to use!

Database:
  # 数据库储存类型 MYSQL 或 SQLITE
  Type: SQLITE
  MYSQL:
    Host: localhost
    Port: 3306
    Database: InteractionVisualizer
    Username: mysql
    Password: password
Messages:
  NoPermission: "&c你没有权限使用该命令!"
  Reload: "&aInteractionVisualizer重新载入!"
  Toggle:
    Usage: "&c用法: /interactionvisualizer toggle <itemstand/itemdrop/hologram>"
    Modes: "&c切换模式: itemstand, itemdrop, hologram"
    Console: "&c请提供玩家名称: /interactionvisualizer toggle <mode> [player]"
    ToggleOn: "&a切换 %s 开启"
    ToggleOff: "&e切换 %s 关闭"
    PlayerNotFound: "&c玩家不在线"

# 方块动画启动设置设置成false便可以关闭动画
Blocks:
  Anvil:
    Enabled: true
  Beacon:
    Enabled: true
  BlastFurnace:
    Enabled: true
  BrewingStand:
    Enabled: true
  CartographyTable:
    Enabled: true
  Chest:
    Enabled: true
  CraftingTable:
    Enabled: true
  DoubleChest:
    Enabled: true
  EnchantmentTable:
    Enabled: true
  EnderChest:
    Enabled: true
  Furnace:
    Enabled: true
  Grindstone:
    Enabled: true
  Loom:
    Enabled: true
  Smoker:
    Enabled: true
  Stonecutter:
    Enabled: true
  ShulkerBox:
    Enabled: true

Entities:
  Villager:
    Enabled: true

# Enable these modules for InteractionVisualizer displays
# ItemStand represents all displays using armorstands and itemframes
# ItemDrop represents all displays using dropped items
# Hologram represents all holograpgic displays using armorstands
Modules:
  ItemStand:
    Enabled: true
  ItemDrop:
    Enabled: true
  Hologram:
    Enabled: true

# 中国网络限制更新功能建议关闭
Options:
  Updater: true
